command:
  - uvicorn
  - booking_engine.api.app:create_app
  - --host=0.0.0.0
  - --port=8000
  - --factory

env:
  - name: LAKEBASE_HOST
    value: "ep-solitary-flower-d30fypjt.database.eu-west-1.cloud.databricks.com"
  - name: LAKEBASE_PORT
    value: "5432"
  - name: LAKEBASE_DB
    value: "hair_salon_db"
  - name: LAKEBASE_USER
    value: "booking_app"
  - name: LAKEBASE_PASSWORD
    value: "ZVMe5zX3nz0GIxGfJPQxEsPFrBjYf9QP65rKlBav0zo"
  - name: LAKEBASE_SCHEMA
    value: "hair_salon"
